
---
- name: Create directory for iso, copy them, mount, insert source.list and update
  hosts: srvbrest
  become: yes
  


  vars:
            source_file: /media/user/Work/Astra Linux/Demo/
            dest_file: /etc/systemd/system/
            source_iso: /media/user/Install/
            dest_iso: /mnt/storage/iso/
            dest_mount_iso: /opt/
            dest_vm: /mnt/storage/vm/


  tasks:
          - name: Create folders for iso & VM
            file:
                 path: "{{ item }}" 
                 state: directory
            with_items: 
            - "{{ dest_iso }}"
            - "{{ dest_vm }}"
                     
          - name: Copy file *.mount
            copy:
                 src: "{{ source_file }}{{item}}"
                 dest: "{{ dest_file }}"
            with_items: 
            - "opt-brest2_3.mount"
            - "opt-smolensk.mount"
            - "opt-smolensk_upd4.mount"
            - "opt-smolensk_dev.mount"
                     
          - name: Create folders for reposetory
            file:
                 path: "{{ dest_mount_iso }}{{item}}"  
                 state: directory
            with_items: 
            - "smolensk"
            - "smolensk_upd4"
            - "smolensk_dev"
            - "brest2_3"

          - name: Copy iso >> "{{ dest_iso }}"  
            copy:
                 src: "{{ source_iso }}{{item}}"
                 dest: "{{ dest_iso }}"
            with_items: 
            - "smolensk-1.6-20.06.2018_15.56.iso"
            - "devel-smolensk-1.6-20.06.2018_15.56.iso"
            - "20191029SE16.iso"
            - "orel-current.iso"
            - "brest-2.3-for-smolensk-1.6-update3.iso"

          - name: Make sure service *.mount is running and enabled
            systemd:
                 daemon_reload: yes
                 state: started
                 name: "{{item}}"
                 enabled: yes
            with_items: 
            - "opt-brest2_3.mount"
            - "opt-smolensk.mount"
            - "opt-smolensk_upd4.mount"
            - "opt-smolensk_dev.mount"
          
          - name: Copy sources.list
            copy:
                 src: "{{ source_file }}sources.list"
                 dest: "/etc/apt/"


          - name: Update_cache apt
            apt:
                 update_cache: yes 
